// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvQku9gcFQnxhblLkwbJ9g_KTEo7bjsYg',
    appId: '1:784742312275:web:7004f55b65001299ea99a6',
    messagingSenderId: '784742312275',
    projectId: 'gamespecs-fa531',
    authDomain: 'gamespecs-fa531.firebaseapp.com',
    storageBucket: 'gamespecs-fa531.appspot.com',
    measurementId: 'G-P1BMLYZN1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb4Ztn1qT-So6oUsgeoD16cjbmYDNVpJQ',
    appId: '1:784742312275:android:ef612215e80fb3d6ea99a6',
    messagingSenderId: '784742312275',
    projectId: 'gamespecs-fa531',
    storageBucket: 'gamespecs-fa531.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3KwVLBusFiqNvMR7i0CTwhHEfsvLO1Qk',
    appId: '1:784742312275:ios:a293cafc5cd104ffea99a6',
    messagingSenderId: '784742312275',
    projectId: 'gamespecs-fa531',
    storageBucket: 'gamespecs-fa531.appspot.com',
    iosClientId: '784742312275-hrc918ds2idrnq1jbkake2ht1b00iiio.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobilodevi',
  );
}
